from dotenv import load_dotenv
import os
import string
from pathlib import Path
from pypdf import PdfReader
from openai import OpenAI
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex
from llama_index.llms.openai import OpenAI
from llama_index.core.evaluation import FaithfulnessEvaluator, RelevancyEvaluator

if load_dotenv():
    print("API key loaded successfully.")
else:
    print("Warning: could not load API key. Check your .env file.")

# --- RAG Concepts ---

# Concepts Q1

# Scenario A: A legal team wants an assistant that can answer questions about their internal policy library — hundreds of PDFs that are updated every quarter.
# RAG would be the best approach for this project as it allow the retrieval of information from a database containing the company's documents, this approach also allows the
# updating of the documents every quarter, which is something needed for this project.

# Scenario B: A startup wants their model to write product copy in a very specific brand voice — a dry, minimalist style that does not appear much online. They have 3,000 examples their in-house writers produced over the years.
# Fine-Tuning would be the best approach for this project mainly because they need something very specific that is not commonly found online, so the model has no examples of it.
# and thus having the 3000 examples provides the ideal conditions for the use of fine tunnning, once trained the model would generate the correct tone without extensive prompt
# templates and/or using a lot of tokens every time a call is made. 

# Scenario C: A data analyst needs to ask an LLM questions about a single two-page report she just received. She does not need this to work for any other document.
# Prompt engineering would be the ideal option in this case as the report is not too long, and this task doesnt need to be repeated multiple times, so the best approach is to 
# attach the document direclty into the prompt saving time  by not requiring any data formatting, chunking, embedding or model training.

# Concepts Q2

# Question: Why is a confidently wrong answer more harmful than one that says "I am not sure"?
# Answer: because it 'sounds right' due to it being well redacted and full of 'logical' explanations and 'facts', so this well redacted false information can
# trick a person without knoledge on the matter being discussed.

# Question: Give one example of a real situation where a confident hallucination could cause harm.
# A chatbot providing false information with absolute confidence can cause widespread harm—ranging from financial and legal consequences to emotional frustration—affecting
# both consumers and businesses alike. If, for instance, the AI misrepresents a product's features and drives an online purchase, the customer will be deeply disappointed
# upon delivery. This inevitably triggers a return process and can permanently damage the company’s reputation.

# Concepts Q3

# 1. Extract text from source documents - The content of the documents is extracted from the source files.
# 2. Split text into chunks - Read text is then split into smaller, manageable chunks for retrieval.
# 3. Convert text chunks into embeddings - Text chunks are converted to embeddings and then stored in a vector database.
# 4. Receive the user's query - The model receives the user's query.
# 5. Embed the user's query - The query gets converted to an embedding, so it is on the same vector space as the text chunks done before.
# 6. Retrieve the most relevant chunks - Most relevant chunks get retrieved, most relevant meaning they are closer in the vector space.
# 7. Inject retrieved chunks into the prompt - The prompt is then augmented using the relevant chunks of text.
# 8. Generate a response from the LLM - A response is generated by the LLM using the augmented context.


# --- Keyword RAG ---

def simple_keyword_retrieval(query, documents, verbose=True):
    """Keyword retrieval using token overlap scoring."""
    stopwords = {
        "a", "an", "the", "and", "or", "in", "on", "of", "for", "to", "is",
        "are", "was", "were", "by", "with", "at", "from", "that", "this",
        "as", "be", "it", "its", "their", "they", "we", "you", "our"
    }
    translator = str.maketrans("", "", string.punctuation)

    query_words = {
        w.translate(translator)
        for w in query.lower().split()
        if w not in stopwords
    }
    if verbose:
        print(f"\nQuery tokens (filtered): {sorted(query_words)}")

    scores = []
    for name, content in documents.items():
        content_words = {
            w.translate(translator)
            for w in content.lower().split()
            if w not in stopwords
        }
        overlap = query_words & content_words
        score = len(overlap)
        scores.append((score, name, content))
        if verbose:
            print(f"[{name}] overlap={score} -> {sorted(overlap)}")

    scores.sort(reverse=True)
    best = next(((name, content) for score, name, content in scores if score > 0), None)
    if best:
        if verbose:
            print(f"\nSelected best match: {best[0]}")
        return [best]
    else:
        if verbose:
            print("\nNo overlapping keywords found.")
        return [("None found", "No relevant content.")]

# Keyword Q1

query = "What are your hours on weekends?"

documents = {
    "menu.txt": "We serve espresso, lattes, cappuccinos, and cold brew. Pastries include croissants and muffins baked fresh daily. Oat milk and almond milk are available.",
    "hours.txt": "We are open Monday through Friday from 7am to 7pm. On weekends we open at 8am and close at 5pm. We are closed on Thanksgiving and Christmas Day.",
    "hiring.txt": "We are currently hiring baristas and shift supervisors. Send your resume to jobs@groundworkcoffee.com.",
    "loyalty.txt": "Join our loyalty program to earn one point per dollar spent. Redeem 100 points for a free drink of your choice.",
}

keyword_q1 = simple_keyword_retrieval(query, documents, verbose=True)
print(f'Selected document: {keyword_q1[0][0]}')

# Question: which document was selected and why?
# Answer: loyalty.txt was the selected document, when running the function we can see that all documents (except menu.txt) got a score of 1, meaning they are all relevant
# based on the keywords, but then the script sorts the selected documents in a reverse mode, making loyalty.txt the first on the list, so the first document gets selected
# and passed to the prompt to generate the answer.

# Keyword Q2

query = "Do you have anything without caffeine?"

keyword_q2 = simple_keyword_retrieval(query, documents, verbose=True)
print(f'Selected document: {keyword_q2[0][0]}')

# Question: Which document was selected?
# Answer: No document was selected
# Question: Whether keyword RAG got this right — and why or why not
# Answer: Keyword RAG got his wrong, it didnt select any document as none of the documents had the exact word used in the prompt, but in reality many words 
# on the document are related and close semantically to the words used in the prompt.
# Question: What kind of retrieval would do better here
# Semantic RAG would do a better job.

# Keyword Q3

query = "How do I sign up for rewards?"

# Question: Before running any code, predict which document will be selected for the query below.
# Answer: I think no document will be selected, mainly because none of the words in the prompt match any of the word on the documents.

keyword_q3 = simple_keyword_retrieval(query, documents, verbose=True)
print(f'Selected document: {keyword_q3[0][0]}')

# --- Semantic RAG Concepts ---

# Semantic Q1

# Question: What is a vector embedding? (1-2 sentences)
# Answer: A vector embedding is a number or list of numbers assigned to a word (or piece of data) that maps it into a numerical space. 
# these embeddings then represent properties of the data so the model can understand it.

# Question:Two text chunks have cosine similarity scores of 0.85 and 0.30 with a given query. Which chunk is more relevant, and what does that number tell you about the relationship between the texts?
# Answer: Cosine similarity goes from -1 to 1, so in this scale 0.85 being closer to 1 makes it more relevant to the query, 0.30 has some relevancy, a number 0 would mean no relevancy. 

# Question:Why can semantic search find a relevant chunk even when none of the exact words from the query appear in the chunk?
# Answer: Using the embeddings and their position on the numerical space, then comparing those positions with the positions of the word used in the query, semantic search finds
# relevance through the distance between words using cosine similarity.

# Semantic Q2

# | Feature                    | Keyword RAG                       | Semantic RAG                             |
# |----------------------------|-----------------------------------|------------------------------------------|
# | What is compared?          | Exact word overlap                | Distance in the numerical space          |
# | What is retrieved?         | Full document                     | A Chunk of the document                  |
# | Can it handle synonyms?    | No                                | Yes                                      |
# | Storage format             | Plain text dictionary             | Vector database                          |
# | Relevance score            | Number of overlapping keywords    | Cosine similarity                        |


# --- LlamaIndex ---

# LlamaIndex Q1

docs = SimpleDirectoryReader("resources/brightleaf_pdfs").load_data()

index = VectorStoreIndex.from_documents(docs)

query_engine = index.as_query_engine(similarity_top_k=3)

questions = [
    "What employee benefits does BrightLeaf offer?",
    "What are BrightLeaf's security policies?",
]

for q in questions:
    print(f"\nQ: {q}")
    response = query_engine.query(q)
    print("A:", response)
    
    for node_with_score in response.source_nodes:
        print(f"Node ID: {node_with_score.node.node_id}")
        print(f"Similarity Score: {node_with_score.score:.4f}")
        print(f"Text Snippet: {node_with_score.node.get_content()[:150]}...")
        print("-" * 30)

# Query 1
# Question: Do the retrieved chunks look relevant to the question?
# Answer: Yes, on this case the model retrieved a relevant chunk of information.
# Question: Does the model's response sound confident and specific, or does it hedge with phrases like "based on the context" or "I'm not sure"? Note what you observe about the tone.
# Answer: the model sounds confident and very specific pointing to the various perks offered by the company for its employees.
# Question: Did anything unexpected get retrieved?
# Answer: From the three chunks retrieved, the used one was relevant to the question, but the following two chunks did not seem relevant at all.

# Query 2
# Question: Do the retrieved chunks look relevant to the question?
# Answer: On this case the model retrieved a relevant chunk of information, and i say relevant as the information is contained on one of the documents provided, but for me
# personally, this document seems not related to this company or to the 'solar energy' industry, seems more like a document from a software company, i would not consider this
# as an AI hallucination but rather a mistake by the people in charge of providing the documents.
# Question: Does the model's response sound confident and specific, or does it hedge with phrases like "based on the context" or "I'm not sure"? Note what you observe about the tone.
# Answer: the model sounds confident and very specific pointing to the various security policies implemented by the company.
# Question: Did anything unexpected get retrieved?
# Answer: From the three chunks retrieved, the used one was relevant to the question, but the following two chunks did not seem relevant at all.

# LlamaIndex Q2

# Query with similarity_top_k=1
query_engine = index.as_query_engine(similarity_top_k=1)
response = query_engine.query(questions[0])

print(f"\nQ: {questions[0]}")
response = query_engine.query(questions[0])
print("A:", response)

for node_with_score in response.source_nodes:
    print(f"Node ID: {node_with_score.node.node_id}")
    print(f"Similarity Score: {node_with_score.score:.4f}")
    print(f"Text Snippet: {node_with_score.node.get_content()[:100]}...")
    print("-" * 30)

# Query with similarity_top_k=5
query_engine = index.as_query_engine(similarity_top_k=5)
response = query_engine.query(questions[0])

print(f"\nQ: {questions[0]}")
response = query_engine.query(questions[0])
print("A:", response)

for node_with_score in response.source_nodes:
    print(f"Node ID: {node_with_score.node.node_id}")
    print(f"Similarity Score: {node_with_score.score:.4f}")
    print(f"Text Snippet: {node_with_score.node.get_content()[:100]}...")
    print("-" * 30)

# Question:Add a comment explaining how the response changed (if at all) and whether more retrieved context is always better.
# Answer: the 'similarity_top_k' parameter controls how many chunks of relevant information to retrieve, on this particular case having more chunks retrieved did not change
# the final answer, but it probably made the engine work a little bit more, so from this example only i can infer that it does not make a difference.

# LlamaIndex Q3

q3 = 'what is the organizational structure of BrightLeaf'

query_engine = index.as_query_engine(similarity_top_k=3)
response = query_engine.query(q3)

print(f"\nQ: {q3}")
response = query_engine.query(q3)
print("A:", response)

for node_with_score in response.source_nodes:
    print(f"Node ID: {node_with_score.node.node_id}")
    print(f"Similarity Score: {node_with_score.score:.4f}")
    print(f"Text Snippet: {node_with_score.node.get_content()[:100]}...")
    print("-" * 30)

# Question: Add a comment explaining what you expected, what actually happened, and what you would change about the system to handle this kind of query better.
# Answer: I expected the model to copmletely hallucinate and make up some information about the organizational structure of the company, instead it retrieved a chunk of text
# that talks about the structure of the employee benefits and redacted it in way that seems to be talking about the structure the company while in reality it isn't.
# One way to hanlde this better would be to attach the title of the parent document to every chunk of text, and use it ehn comparing the similarity of the piece of text with the query.

# LlamaIndex Q4

llm = OpenAI(model="gpt-4o-mini", temperature=0.2)

faithfulness_evaluator = FaithfulnessEvaluator(llm=llm)
relevancy_evaluator = RelevancyEvaluator(llm=llm)

q4 = "What employee benefits does BrightLeaf offer?"
response = query_engine.query(q4)

print(response)

faithfulness_result = faithfulness_evaluator.evaluate_response(query=q4, response=response)
print("Faithfulness Evaluation: " + str(faithfulness_result.score))

relevancy_result = relevancy_evaluator.evaluate_response(query=q4, response=response)
print("Relevancy Result: " + str(relevancy_result.score))

# query with lower quality response expected
q4_lower = "How many total employees does BrightLeaf Solar currently employ across all of its regional offices?"

response = query_engine.query(q4_lower)

print(response)

faithfulness_result = faithfulness_evaluator.evaluate_response(query=q4_lower, response=response)
print("Faithfulness Evaluation: " + str(faithfulness_result.score))

relevancy_result = relevancy_evaluator.evaluate_response(query=q4_lower, response=response)
print("Relevancy Result: " + str(relevancy_result.score))

# Question: What does a faithfulness score of 1.0 mean? What would a score of 0.0 indicate?
# Answer: a faithfulness score of 1.0 means that the answer provided is found on the provided documents, while a score of 0 indicates that the answer
# cannot be found anywhere on the provided documents, meaning the model hallucinated or pullled information from somewhere else.
# Question: What does a relevancy score measure, and how is it different from faithfulness?
# Answer: Relevancy score means that the answer is relevant to the query from a semantic point, it is different from faithfulness as it evaluates if the answer
# is relevant to the question not if the the answer is found on the supporting documents.
# Question: Did the scores change between your two queries? If so, why do you think that happened?
# Answer: Yes, the scores changed, on the first question both scores were 1, but on the low level answer expected question the faithfulness score was 0 while  the 
# relevancy score was 1, this means that the answer was 100% relevant to the query (relevancy 1), from a semantic standpoint, but the fact it stated, could not be found anywhere on the
# provided documents (faithfulness 0)
# Question: What is the "LLM-as-a-judge" approach, and why is it used for RAG evaluation instead of a simple accuracy metric?
# Answer: On this approach, an LLM is used to assess, score and evaluate the outputs of the RAG pipeline, it is used because LLM's can evaluate abstract qualities like semantic meaning, 
# nuance, and logic, which traditional accuracy metrics cannot capture.

